### ISSUE TITLE
Flipping vertically does not work

### ISSUE THREAD

**Issue by beaur** [manumaticx/TiAndroidFlip#4]
Can not get the view to flip vertically even after setting the orientation parameter

**Comment by AppWerft** [comment]
same.  Manu, do you have time to solve it? Maybe in this line https://github.com/manumaticx/TiAndroidFlip/blob/master/android/src/se/emilsjolander/flipview/FlipView.java#L1230 you have to use `equals` instead of  `==`

**Comment by manumaticx** [comment]
Hey, I've just pushed a new version. There was indeed a wrong string comparison. Can sombody please verify the bugfix, I didn't have the time to test it, sorry.

**Comment by AppWerft** [comment]
Ah I see, you have modified in thirdparty sources, I will try.

**Comment by AppWerft** [comment]
It works as aspected. In you manifest is a little mistake. 

architectures: armeabi-v7a x86

**Comment by manumaticx** [comment]
@AppWerft this didn't compile with 6.0.0.GA - any idea?

**Comment by AppWerft** [comment]
You need some modifyings.
1. manifest: level 3 and only two architectures, and min level
2. build.configuration: path to new SDK

**Comment by manumaticx** [comment]
I did in d41cc4bc9a43dd7fc9c5226dc5724dfd5d9b82f4

**Comment by manumaticx** [comment]
If I use `architectures: armeabi-v7a x86` it says:
```
check.build.arch:
     [echo] Architectures in manifest: armeabi-v7a x86
     [echo] Compiled binary architectures: armeabi;armeabi-v7a;x86

BUILD FAILED
/Users/manuel/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/module/android/build.xml:376: The following error occurred while executing this line:
/Users/manuel/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/module/android/build.xml:378: There is discrepancy between the architectures specified in manifest and compiled binary.
```

**Comment by AppWerft** [comment]
Ok is well known "bug", Clean your libs and build folder and try it again.

**Comment by manumaticx** [comment]
Yep. Thanks. That worked :)
