### ISSUE TITLE
v 7.1.0

### ISSUE THREAD

**Issue by AppWerft** [manumaticx/TiAndroidFlip#5]
I try this:

version: 4.0.0
apiversion: 4
architectures: arm64-v8a armeabi-v7a x86
description: Android FlipView for Titanium
author: Manuel Lehner
license: MIT
copyright: Copyright (c) 2014 by Manuel Lehner

# these should not be edited
name: AndroidFlip
moduleid: de.manumaticx.androidflip
guid: c748346d-7c10-48aa-9821-c071859d616f
platform: android
minsdk: 7.1.0

But the build process `ti build -b -p android` hangs on ` Packaging the module`. Any ideas?

**Comment by manumaticx** [comment]
@AppWerft try removing the _documentation_ folder.
It's probably the same issue with the wrong module directory structure, like here: 
https://github.com/ricardoalcocer/actionbarextras/issues/126#issuecomment-405929224

**Comment by AppWerft** [comment]
Thanks it works I will do a PR. ;-)

**Comment by manumaticx** [comment]
solved #6
